version: '3'

services:
  wg_1:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-wg
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - "./vpn:/vpn"
    environment:
      - "WG_CONF=vpn/wg/conf/tg_uk_1.conf"
      - "PORT=50102"
  wg_2:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-wg
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - "./vpn:/vpn"
    environment:
      - "WG_CONF=vpn/wg/conf/tg_uk_2.conf"
      - "PORT=50104"
  wg_3:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-wg
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - "./vpn:/vpn"
    environment:
      - "WG_CONF=vpn/wg/conf/tg_uk_3.conf"
      - "PORT=50105"
  wg_4:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-wg
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - "./vpn:/vpn"
    environment:
      - "WG_CONF=vpn/wg/conf/tg_uk_4.conf"
      - "PORT=50106"
  wg_5:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-wg
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - "./vpn:/vpn"
    environment:
      - "WG_CONF=vpn/wg/conf/tg_uk_5.conf"
      - "PORT=50107"
    
    