FROM alpine:3.15.0

RUN apk update && \
    apk add wget openvpn curl


# Pull + set up goproxy
RUN mkdir goproxy && \
    wget https://github.com/snail007/goproxy/releases/download/v11.4/proxy-linux-amd64.tar.gz -O goproxy/proxy.tar.gz && \
    cd goproxy && tar -xvf proxy.tar.gz && chmod +x proxy

# Copy + execute startup script
COPY startup_vpn.sh /startup.sh
CMD ["/bin/sh", "/startup.sh"]